<a href="https://colab.research.google.com/github/kulvanth5/optimization-techniques/blob/main/Copy_of_Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# a simple way to create a multi-dimensional array
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#will create a matrix with specified dimensions with all the values of it as zeros
b = np.zeros((3,3),dtype=complex)

b

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

In [ ]:
# in addition to arange , also allows us to specify no.of values to be inserted into the matrix

# reshape is used to give a view of an ndim array in some other dim rather than converting it
# resize is used to convert existing array into some other specified dim
np.linspace(1,30,9,dtype=int).reshape(3,3)

array([[ 1,  4,  8],
       [11, 15, 19],
       [22, 26, 30]])

In [ ]:
def f(i,j):
  return i+j

# create a new matrix with values based on the definition of a function
new = np.fromfunction(f,(3,3))

new

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [ ]:
# new.shape will print the dimension of the marix
# new.ndim will print how many dimensions does the matrix has
print(new.ndim,new.shape)

3 (3, 3, 3)


In [ ]:
# multiplication of two matrices
np.matmul(new,b)

array([[[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]])

In [ ]:
# checks for each value of the matrix and generates a new one
new < 5

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True, False]],

       [[ True,  True,  True],
        [ True,  True, False],
        [ True, False, False]]])

In [ ]:
# np.nan is a special value that represents a "Not a Number"
# np.inf represents infinity

#converts an ndim array to 1dim array
new.flatten()

#just gives a view of ndim array in 1dim rather than converting it
new.ravel()

array([0., 1., 2., 1., 2., 3., 2., 3., 4., 1., 2., 3., 2., 3., 4., 3., 4.,
       5., 2., 3., 4., 3., 4., 5., 4., 5., 6.])

In [ ]:
#to transpose a matrix
a.transpose()

#to align all the rows horizontally , similarly vstack to align all the rows vertically
np.hstack(new)

array([0., 1., 2., 1., 2., 3., 2., 3., 4., 1., 2., 3., 2., 3., 4., 3., 4.,
       5., 2., 3., 4., 3., 4., 5., 4., 5., 6.])

In [ ]:
#indexing in array
a[0,1,2]

#slicing in an ndim array
a[0:1:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
#we can add a scalar to all the elements of an array
b=b+3-1j

temp = np.fromfunction(f,(3,3))

temp + b


array([[3.-1.j, 4.-1.j, 5.-1.j],
       [4.-1.j, 5.-1.j, 6.-1.j],
       [5.-1.j, 6.-1.j, 7.-1.j]])

In [ ]:
#will return the index of element with maximum value in the array
np.argmax(a)

#will return the index of element with minimum value in the array
np.argmin(a)

#will return the min value of each column , for axis=1 returns the min value of each row. Similarly for max as well
new.min(axis=0)

array([0., 1., 2.])

In [ ]:
x = np.array([[22,-54,2345],[-589,77,0],[52,-798,99]])

#for 2d array , by default sorts the array row wise
x.sort()

#sorts the array column wise
x.sort(axis=0)

x

array([[-798,    0,   77],
       [-589,   22,   99],
       [ -54,   52, 2345]])